name: Windows Server 2022 - RDP con Chrome, VLC y Ngrok

on:
  workflow_dispatch:

jobs:
  rdp-windows:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 horas
    steps:

    - name: 👤 Crear usuario RDP
      run: |
        net user itzy 1tZy123! /add
        net localgroup administrators itzy /add
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      shell: powershell


    - name: 📦 Descargar Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath .
      shell: powershell

    - name: 🔐 Autenticarse con Ngrok
      run: .\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      shell: powershell

    - name: 🚪 Iniciar túnel RDP (Ngrok)
      run: .\ngrok.exe tcp 3389
      shell: powershell
